---
deployment:
  tasks:
    # Define la ruta de despliegue principal (la carpeta pública de tu dominio).
    # Asegúrate de que '/home/cftechbr/' coincida con tu nombre de usuario de cPanel.
    - export DEPLOYPATH=/home/cftechbr/public_html/

    # Tarea 1: Copia todo el contenido de la carpeta 'public' de tu repositorio
    # a la carpeta 'public_html' de tu servidor.
    - /bin/cp -R public/. ${DEPLOYPATH}

    # Tarea 2: Copia las carpetas con la lógica de la aplicación (app, config)
    # a un directorio superior (/home/cftechbr/), fuera del alcance público.
    - /bin/cp -R app/ ${DEPLOYPATH}../
    - /bin/cp -R config/ ${DEPLOYPATH}../
